### ISSUE TITLE
Optimize Chunk System

### ISSUE THREAD

**Issue by DasCapschen** [Libre-TrainSim/Libre-TrainSim#103]
I'm sure you have noticed a stutter while driving around, especially noticable on Hainfurt.

I've done some quick measuring, and found the following:
- some chunks load 0 Rails, 0 Track Objects, etc. Loading such a chunk takes less than 100 micro seconds
- loading 1 object (rail, or track object, or flora, etc) takes about 1000-3000 microseconds
- calling `save_value()` at the end of loading takes ~50.000 micro seconds, regardless of objects loaded

So what could be done about this?
- using threads to load Buildings, Flora and Track Objects in parallel might be helpful. 
    + Starting a thread takes ~100µs, joining a thread does also take ~100µs
    + we can have 3 threads: track objects, flora, buildings
    + that is 600µs of delay we are *adding*
    + if 1 object takes 1000µs to load, then loading 1 track object, 1 flora and 1 building in parallel will also take 1000µs, instead of 3000µs when done sequentially
    + 3000-1000+600 = 1400µs that we would save
    + so using threads makes sense as soon as we load more than 1 object in parallel
    + using threads does NOT make sense when: we only load 1 type of object (for example only track objects, but no flora and no buildings)
    + the decision to use threads of not could be in an `if` check before the function
- do **not** use `get_value` and `set_value` for `unloaded_chunks`, just keep it in memory. These methods *always* cause a Disk Read or Disk Write, which is relatively slow.
    + if they do need to be saved to disk, only load them at the start, and save them before the game ends? Alternatively only save after loading *all* chunks, not after loading *1* chunk

There might be even more things that can be done about this, but that is all I checked so far.  
I might add more information to this issue as I discover it.

**Comment by Jean28518** [comment]
You are right! That's a problem I have on my internal Todo list. I will enhance the jSaveModule, that it automatically stores the values in memory after calling them

**Comment by Jean28518** [comment]
jSaveModule got a cache system, so saving and loading from .save file got very fast. 

WIll now concentrate on multithreading...
