### ISSUE TITLE
Use Text to Speech where no sound files are provided

### ISSUE THREAD

**Issue by HaSa1002** [Libre-TrainSim/Libre-TrainSim#111]
Using TTS, we could add speach output and add dynamic announcement elements like late arrivals.
We could use a library like this: https://github.com/bruvzg/godot_tts

**Comment by Jean28518** [comment]
Mhmm.. 
If someone needs sound files I record them :)
For me this feature is not necessary at the time

**Comment by bodamat** [comment]
Interesting idea and interesting project. I want to try

**Comment by bodamat** [comment]
It's an interesting idea, but the real voice is much better

**Comment by HaSa1002** [comment]
It would only make sense if we had the same voice processor as used in real life

**Comment by bodamat** [comment]
but we don't have a voice processor like in real life. I hear some websites improving this system and have even emotions, but it is not free.

**Comment by HaSa1002** [comment]
I have another idea, where we create some dynamic voice lines from text using prerecorded parts. But it is not really needed currently

**Comment by bodamat** [comment]
As result, it can sound strange. Move this task to the future :)

**Comment by HaSa1002** [comment]
Closing this issue as there is no need to have that right now.
