### ISSUE TITLE
OpenBVE / Custom Keyboard Settings

### ISSUE THREAD

**Issue by IntinteDAO** [Libre-TrainSim/Libre-TrainSim#112]
Hello, I have activated the advanced train control mode (:P) and it works differently than in OpenBVE. Maybe an option to set the control as in OpenBVE would be useful?

SIPA - End
Emergency Break - 1
F - Forward direction
V - Reverse direction
Z - Forward
A - Gear up/down up to neutral
Q - Decrease gear
Horn - Space

**Comment by Jean28518** [comment]
duplicate to #35 
Thanks for the OpenBVE layouts :)
