### ISSUE TITLE
Assign Signal to station

### ISSUE THREAD

**Issue by Jean28518** [Libre-TrainSim/Libre-TrainSim#116]
Needed for #107.

if set the signal of the station is red until the planned departure of train.
Station (=or Player) should control signal, Signal code don't has to be changed

**Comment by HaSa1002** [comment]
I would prefer if the signals work more autonomous and act like a block or path system. We can still create a new StationSignal class that is connected to a station and acts different

**Comment by Jean28518** [comment]
I wouldn't.
The station should control the signal.
Then mod support for other signals isn't affected.

We already have a block signal function.

**Comment by DasCapschen** [comment]
I agree with Jean that it's fine to have this logic in a single Signal script, and we don't need a separate StationSignal.

But I agree with HaSa that signals should in the future be refactored to make a proper block system. Right now it doesn't really support more than 1 train, especially in different directions :smile:
But that is a separate issue.

**Comment by Jean28518** [comment]
Done with PR #278
