### ISSUE TITLE
Lacks instruction for use from git tree, maybe lacks data files

### ISSUE THREAD

**Issue by ydirson** [Libre-TrainSim/Libre-TrainSim#123]
People willing to take a run from git may not be familiar with godot, and could use directions.

I've tried myself to launch with godot3-runner on Debian10 (where godot 3.0 is not sufficient, and I had to google for the `_load_settings_text: Condition ' config_version > 3 ' is true. returned: ERR_FILE_CANT_OPEN` error message to realize that I need at least v3.1), and on Debian 11 (with godot 3.2) where it seems it cannot find some resources:

```
Loading resource: res://Translations/Ingame.de.translation
ERROR: load_interactive: Condition "err != OK" is true. Returned: Ref<ResourceInteractiveLoader>()
   At: core/io/resource_format_binary.cpp:998.
ERROR: _load: Condition "found" is true. Returned: RES()
   At: core/io/resource_loader.cpp:278.
Loading resource: res://Translations/Ingame.en.translation
ERROR: load_interactive: Condition "err != OK" is true. Returned: Ref<ResourceInteractiveLoader>()
   At: core/io/resource_format_binary.cpp:998.
ERROR: _load: Condition "found" is true. Returned: RES()
   At: core/io/resource_loader.cpp:278.
...
```

Now maybe those files are just missing from git :)

**Comment by HaSa1002** [comment]
These files do exist 🤔 Try to delete the `.import` folder. Please note the current Godot version is 3.3.3.

But we should include a note about the latest stable Godot version and with 3.4 around the corner-ish we should clearify that as well, because there are going to be config file changes which will lead to git noise, if we use multiple versions.

**Comment by ydirson** [comment]
I do not have a  `.import` folder to delete.

The only translation files I get from git are those: 
```
Libre-TrainSim$ find -name "*transl*"
./src/Trains/JFR1/JFR1.en.translation
./src/Trains/JFR1/JFR1.de.translation
```

I note there is a `*.translations` pattern in `.gitignore` (so it may be a mistake to have 2 of them commited).

I guess they are generated from .csv files, so there may be some build steps to be made before the project can run (which bring us back the "build instructions" problem). I'll have to check whether it is something 3.3 generates all by itself, but 3.2 definitely has problems here.

**Comment by Jean28518** [comment]
Thanks for mentioning the .translation files! Got removed now from master branch.

Please use the newest Godot Version: https://godotengine.org/download
Then you won't have any problems.
Added this to our Contribute Page: https://github.com/Jean28518/Libre-TrainSim/wiki/Contribute-to-Libre-TrainSim

**Comment by ydirson** [comment]
Yes it works with 3.3.  However, on first run we still see a number of errors about missing resources, until godot apparently decides it has to generate its own stuff.  It would be useful to mention this in user instructions, along with possibly "how to generate the stuff" - the equivalent of a "configure; make" invocation.

**Comment by Jean28518** [comment]
What should I write in this instruction?

    Please open up the project with the newest GoDot 3 version and wait for 5 minutes while godot imports all resources automatically

?
