### ISSUE TITLE
Add PZB

### ISSUE THREAD

**Issue by DasCapschen** [Libre-TrainSim/Libre-TrainSim#131]
For more realistic behaviour, we should implement more security systems, like PZB.

I would like to implement this myself, leaving this issue here as a TODO / Documentation of how PZB works.

I recommend these sources for explanations :)
https://de.wikipedia.org/wiki/Punktf%C3%B6rmige_Zugbeeinflussung
https://www.youtube.com/watch?v=M5cfjwSpIds
http://tf-ausbildung.de/BahnInfo/oberezugart.htm

# For passenger trains (pzb type 85): 
## Signals
- add 1000 Hz magnet on pre-signals
- triggers PZB warning if next main signal is Red or has a speed limit
     + 85 lamp starts blinking, 1000 Hz lamp illuminates
- driver must press "PZB Acknowledge" button within 4 seconds (else train emergency brakes)
- slow down to 85km/h within 23 seconds (else emergency brakes)
- after 700m, 1000 Hz mode turns off. (1000 Hz lamp turns off)
- If signal is green, press "PZB Free" button to exit monitoring (85 lamp stops blinking)
     + continue your journey like normal
     + if "PZB free" was pressed, but 1000 Hz lamp is on, or signal is red: emergency braking after passing 500 Hz magnet
- If signal is red, slow down to 65km/h *before* the 500 Hz magnet
- after passing 500 Hz magnet (500Hz lamp turns on), slow down to 45km/h within 153 meters
    + you *cannot* use "PZB free" if 500 Hz mode is on! Use it *before* passing the 500 Hz magnet!
- if signal is green: stay below 45km/h and pass the signal
- if signal is red: stop before the signal (2000 Hz magnet) and wait until it is green, else emergency brakes
    + you can press and hold the "PZB command" button while driving over the 2000 Hz magnet / red signal without getting emergency brakes (up to 40km/h only!) (if you're allowed to :wink: by a replacement signal or otherwise)
- accelerate to pass the signal. 250m *after* the signal, monitoring turns off. (do not go over 45km/h within those 250 meters!)
- Continue your journey like normal.

## Restrictive Mode
If at any point, the train stopped or is going below 10km/h for more than 15 seconds:
- enter restrictive monitoring (70 and 85 lamp blink alternating)
- limit train to 45km/h (1000 Hz mode / train starts for the first time) or 25km/h (500 Hz mode)
- press "PZB Free" button to release from restrictive monitoring (this does *not* work if 500 Hz mode is on!)
- if train was released:
     + if 1000 Hz magnet is passed, go to *normal* 1000 Hz mode (not restrictive)
     + if 500 Hz magnet is passed, emergency brakes come on

**Comment by Jean28518** [comment]
Good idea!
I don't know if I personally have the time to implement that to v0.9
I will concentrate on #107  as my next big project

**Comment by DasCapschen** [comment]
Like I said, I want to implement it myself, and I've actually already started :)
