### ISSUE TITLE
I need help (Fix display of addon folder)

### ISSUE THREAD

**Issue by Damrak2021** [Libre-TrainSim/Libre-TrainSim#134]
Hello Jean,

Sorry that I use Google Translate, but my English is not good enough anymore.

I downloaded Libre Train Sim and unpacked everything, but can not play, since I do not know where I have to put the content, so the .pck files. The directory what Ben is displayed to me, I found on my Mac, but there the .pck files can not be reckoned. Something I'm fundamentally wrong. I would be very grateful if you could explain the installation to me again.

Thank you in advance.

Warm greetings

Andy

## ToDo:
- [ ] Change addons directory message
- [ ] Add 'open in filemanager' button

**Comment by HaSa1002** [comment]
Hi @Damrak2021,
which version do you downloaded?
In the latest development version 0.9 this was already fixed by #114. Speaking of which, we should fix the displayed message and add a button to open the directory.

**Comment by Jean28518** [comment]
v0.9 isn't released yet and is very unstable
Added to ToDo!

**Comment by Jean28518** [comment]
done :)
