### ISSUE TITLE
Editor can't be loaded after signal merge

### ISSUE THREAD

**Issue by HaSa1002** [Libre-TrainSim/Libre-TrainSim#143]
The editor wants to preload SpeedLimits, as they were split in #125.
https://github.com/Jean28518/Libre-TrainSim/blob/04b40839f71bad5d989d436d4dc38c4fa8295064/src/addons/Libre_Train_Sim_Editor/Data/Scripts/Editor.gd#L439-L443

**Comment by HaSa1002** [comment]
CC @DasCapschen

**Comment by DasCapschen** [comment]
Oops, you are right, that file does not exist anymore 😅 
So the old `SpeedLimit.tscn` should be replaced by `SpeedLimit_Lf7.tscn`, and `WarnSpeedLimit.tscn` (if that is used anywhere) should be replaced by `WarnSpeedLimit_Lf6.tscn`.

I can fix this in a PR tomorrow, and will also check for any additional signal related reference I might have overlooked 🙂
