### ISSUE TITLE
Change Grass Mesh

### ISSUE THREAD

**Issue by DasCapschen** [Libre-TrainSim/Libre-TrainSim#148]
Current the grass mesh used as the ground is so big that the UV mapping has floating point errors, which results in the Grass texture flickering weirdly. We should probably split it into multiple smaller meshes. 
This can be done in the already existing `generate_grass_panes` in Editor.gd

**Comment by HaSa1002** [comment]
I did a small test, replacing our grass with the first grass, I found on ambientCG (https://ambientCG.com/a/Grass004). When we have a proper terrain editor, we can blend multiple textures and fix the very obvious repeat

<details>
<summary>Old grass</summary>

![grafik](https://user-images.githubusercontent.com/14185889/137211891-702c3ff2-d910-4c2e-a64d-ac03f988e028.png)


</details>

<details>
<summary>1k</summary>

![grafik](https://user-images.githubusercontent.com/14185889/137211046-4ae0cbbf-74c1-4f2b-923f-337588bb98e3.png)

</details>

<details>
<summary>2k</summary>

![grafik](https://user-images.githubusercontent.com/14185889/137211611-17671534-b07e-46a8-9b53-d1e1258ebd48.png)

</details>
