### ISSUE TITLE
Add drag and drop support for track building

### ISSUE THREAD

**Issue by HaSa1002** [Libre-TrainSim/Libre-TrainSim#151]
It would improve the usability of the editor immensely, if dragging of tracks or their contact points are implemented.
This way you drag a contact point and move it with your mouse to destination and the track would update realtime to approximatly match the desired target point. Refer to the track building in Transport Fever for inspiration.

Understanding the track building as part of our gameplay would improve the way people interact with the system. They would have fun using the editor and thus like to create own tracks

**Comment by DasCapschen** [comment]
Drag and Drop for track building should be no problem. We can easily calculate the rail.
https://www.geogebra.org/classic/yrhtghga

And implementing the actual dragging should not be that hard either, we can just project the mouse position to world coordinates. And when we add heightmaps, we can do a raycast to find the current height.

I'll try to have a go at this.
