### ISSUE TITLE
game crashes 

### ISSUE THREAD

**Issue by Djdjdjfjfmckcjcjchchxjjfjfjfj** [Libre-TrainSim/Libre-TrainSim#157]
Game crash

**Comment by DasCapschen** [comment]
Maybe give us some information about this crash?
What version of the game? 0.8 or github master?
What platform? Windows, Mac, Linux, Android?
If Windows or Linux, what are you system specs? (CPU, GPU, RAM, Windows Version / Linux Distro)
Attach a log of the crash?

**Comment by HaSa1002** [comment]
Thank you very much for the issue. Can you please provide some more details?
Which version do you use?
Which OS do you run?
Can you please upload the log file found in the user data directory?
Windows: `%APPDATA%\Godot\app_userdata\Libre TrainSim\logs`
macOS: `~/Library/Application Support/Godot/app_userdata/Libre TrainSim/logs`
Linux: `~/.local/share/godot/app_userdata/Libre TrainSim/logs`
