### ISSUE TITLE
Releasing first Version of Editor

### ISSUE THREAD

**Issue by Jean28518** [Libre-TrainSim/Libre-TrainSim#16]
- [x] Adding more Feedback in Editor Tools
- [x] Releasing the first Version of Editor

**Comment by mszekiel** [comment]
It would be great to have a in-game editor to create sceneries without the Godot engine. And save a scenery to some kind of data structure, for eg. json, csv, binary. Then you'll be able to save and load multiple sceneries created inside editor. That would require main menu and these possible flows: 
Main menu -> Game
Main menu -> Editor

To think about.

**Comment by Jean28518** [comment]
Thanks!
But at first I have to implement the save file system.
Almost all data is already saved in a cfg file.
Yeah, maybe I will begin with an ingame Editor. 
Building Tracks should be doable.
I will think about it ;)
