### ISSUE TITLE
Editor Camera Improvements

### ISSUE THREAD

**Issue by HaSa1002** [Libre-TrainSim/Libre-TrainSim#165]
The current editor camera is not nice. There are some improvements needed
- [x] Camera should move with MMB on xz Plane
- [x] Camera should move on local xz Plane on Alt+MMB
- [x] Camera should orbit around intersection point in view direction with Shift+MMB
- [x] Camera should zoom on Ctrl+MMB
- [x] Camera should be moveable up and down
- [x] Camera should zoom on scroll
- [x] Cursor should end where it was captured

Some of those improvements should be ported to the game camera as well.

**Comment by DasCapschen** [comment]
ingame free camera and editor camera use the same script, iirc, so the improvements would automatically carry over :)

**Comment by HaSa1002** [comment]
That needs to change. Neither do I want MMB panning in the cabin nor do I want to press RMB to move in the game. It simplifies the code, even if we have some code duplication.

**Comment by DasCapschen** [comment]
No, not the camera in the cabin, just the free camera that's enabled with `0`.
But true, we might want that camera to behave differently too.
