### ISSUE TITLE
Power line is not correctly updated in editor

### ISSUE THREAD

**Issue by HaSa1002** [Libre-TrainSim/Libre-TrainSim#167]
It is just a straight line
![grafik](https://user-images.githubusercontent.com/14185889/137033545-e5e283e2-c1c2-461b-be36-0f6c5a3e9638.png)

## To Do
- [x] When adding an electric rail, some standard poles should be added automatically
- [ ] This Option should be toggable (default: true)

**Comment by Jean28518** [comment]
For that the rail needs a Track Object called "Poles", then it updates the power lines correctly.

**Comment by HaSa1002** [comment]
Yeah. But we should add the poles automatically if an electric track is build.

**Comment by Jean28518** [comment]
Just added, to ToDo ;)
