### ISSUE TITLE
Test track button does not load the map

### ISSUE THREAD

**Issue by HaSa1002** [Libre-TrainSim/Libre-TrainSim#187]
It just packs the PCK file and goes back to the main menu. It looks more like a bug than a feature.

**Comment by Jean28518** [comment]
This is how it worked:
-> Select "Test Track" in Editor
-> Packs an temporary pck, loads it in, and opens main menu
-> main menu changes automaticly to track selection where the content of the temporary .pck should be visible..

**Comment by HaSa1002** [comment]
That can't work more than once as the PCK file won't be loaded a second time. I would favor a solution that works directly from the editor and quits to the editor. IIRC, I moved the play menu in its own scene. So it should be easily possible.

**Comment by Jean28518** [comment]
> That can't work more than once as the PCK file won't be loaded a second time

You are able to overwrite. In my tests that worked quite fine. Multiple times.

Using the files directly from the editor folder is much more complicated: The Basic resources are at a complete other path as the track files and new resource files. By loading in the .pck we can garantee that everything, which belongs to the track, is available under res://. 

Then we also don't have any other problem with the parsed .obj, .ogg, .... files. Then everyting is available under res://.import/

The suggestion with the main menu sounds good!

**Comment by HaSa1002** [comment]
> You are able to overwrite. In my tests that worked quite fine. Multiple times.

I know, but as you disable overwriting files, I didn't get that. I understand, you added the same loading again, just with overwriting enabled.

> Then we also don't have any other problem with the parsed .obj, .ogg, .... files. Then everyting is available under res://.import/

Good point.

**Comment by DasCapschen** [comment]
Is this fixed with #228 ?

**Comment by HaSa1002** [comment]
Nope.

**Comment by Jean28518** [comment]
For me this one is not relevant enough for the release of v0.9

**Comment by HaSa1002** [comment]
1.0 its then

**Comment by Jean28518** [comment]
We have to simplify the test and export buttons in the scenario and track editor. At the moment their functions look broken and don't make sense in every case.
