### ISSUE TITLE
Chunksystem spawns a ton of landscape chunks when moving up

### ISSUE THREAD

**Issue by HaSa1002** [Libre-TrainSim/Libre-TrainSim#193]
It spawns like 300 mesh instance nodes with the grass mesh.

**Comment by DasCapschen** [comment]
It should spawn 4 per chunk. And I think when a chunk loads, all its neighbours also load. 
So you could potentially create 9 * 4 = 36 grass meshes in one chunk load.

Though it really should not spawn 300 mesh instances...
