### ISSUE TITLE
PZB Display differs from display in train and extra view (F1)

### ISSUE THREAD

**Issue by Jean28518** [Libre-TrainSim/Libre-TrainSim#199]
![image](https://user-images.githubusercontent.com/39700889/137803904-56589a14-f345-4b6b-9b6d-1b93411ff19c.png)

Image should explain everything :)

**Comment by HaSa1002** [comment]
👀 Maybe caused by delayed updates of the texture?

**Comment by DasCapschen** [comment]
I was pretty sure that the overlay in the HUD and the Screen come from the same render texture? So how can this happen? 🤔
