### ISSUE TITLE
Bug tutorial in not easy mode  

### ISSUE THREAD

**Issue by bodamat** [Libre-TrainSim/Libre-TrainSim#20]
When I choose not easy mode, tutorial for use keyboard for acceleration and break not change.

**Comment by Jean28518** [comment]
Thank you, I will fix this!

**Comment by bodamat** [comment]
I realized. You did it a little differently. You did two different tutorials to control. It is probably better to just pick the option to choose easy mode for the first tutorial and be sure to put easy mode for the second tutorial. Or edit tutorial text for different mode.

**Comment by Jean28518** [comment]
Fixed

**Comment by bodamat** [comment]
Thanks!
