### ISSUE TITLE
Sound played in pause menu

### ISSUE THREAD

**Issue by Jean28518** [Libre-TrainSim/Libre-TrainSim#200]
When the game is in pause menu the sound is playing further on.

The sound should be stopped when paused.

**Comment by HaSa1002** [comment]
Yeah, we just need to react to the notification and pause the stream.
And Issue/Pull Request 200 🥳.

**Comment by DasCapschen** [comment]
I believe this is a jAudioManager bug then, with it not reacting to Pause?
Adding `audioStreamPlayer.pause_mode = Node.PAUSE_MODE_STOP` for `play_game_sound()` should fix this, I believe.

Actually, this is already the case for game sounds, but not for music.
