### ISSUE TITLE
getPathFromToHelper crash

### ISSUE THREAD

**Issue by DasCapschen** [Libre-TrainSim/Libre-TrainSim#203]
Function `getPathFromToHelper` in Wagon.gd:
```gdscript
if connectionN.is_in_group("PassengerPathNode"):
```
"attempt to call is_in_group on null instance"

**Comment by DasCapschen** [comment]
The crash has temporarily been "fixed" by adding a null check. But that is treating the symptoms, not the cause.
We still need to figure out why this goes wrong.

**Comment by DasCapschen** [comment]
This causes People to stick to the train instead of getting in and sitting on a seat.
This is a **blocker** for 0.9!!

**Comment by HaSa1002** [comment]
Okay that one can be fixed with NodePaths. In one of the changes to the trains, the structure was changed and thus all of the logic broke. Using nodepaths instead of strings should fix our issue.
