### ISSUE TITLE
macOS Version can't launch

### ISSUE THREAD

**Issue by ghost** [Libre-TrainSim/Libre-TrainSim#209]
macOS Version doesn't work, .app file is damaged.

![grafik](https://user-images.githubusercontent.com/59450459/139588618-9d68a067-30dc-4850-a7c5-004880e42543.png)

**Comment by HaSa1002** [comment]
Hello @matteodev8 and thank your for your first issue here 🥳.
Unfortunatly macOS builds are a problem for non-mac developers. As you may know, Apple requires apps to be notarized and signed to execute them. This is a known issue. You can find some background information here: https://github.com/godotengine/godot/issues/48076.

Maybe, you can try to follow the steps described here: https://disable-gatekeeper.github.io/

Interesting resources may be:
 * https://github.com/godotengine/godot-docs/pull/5105/files#diff-5bf27dea79e2c1107e1bddce9da1caaf15b4dfdf122252f0fde7391b188f87d1 (How to do ad hoc sign, 3.5 unfortunately(?))
 * https://github.com/godotengine/godot-docs/pull/5105/files#diff-22642977ac61ba74dc5fd98296117f5de20ed822e0d0f4b69f324fa1987458ab (how to run a mac build)

As we are neither a legal entity nor do we have 100 spare dollars there is only so much we can do about this issue. Hopefully, we can improve the situation a little bit, once I improved our CI runs. Please let me know if the steps above did help.

**Comment by ghost** [comment]
> .

Hello. The signing issue is not a problem. There are 2 ways to bypass that.

1. Right click on the app -> Shift + Left Click on 'Open'

or

2. Disable Gatekeeper: sudo spctl --master-disable

**Comment by HaSa1002** [comment]
Which version do you used?

**Comment by ghost** [comment]
> Which version do you used?

0.8

**Comment by HaSa1002** [comment]
Can you please try to run that version (it is not notarized nor will it have the execution flag set):
https://github.com/Libre-TrainSim/Libre-TrainSim/suites/4208753988/artifacts/108715823

**Comment by HaSa1002** [comment]
Hey @matteodev8,
please try the following steps:
> If the application was packaged in a ZIP archive, this could be due to the executable (+x) attribute being missing on the binary contained in the .app bundle. To solve this:
>
> 1. Open a terminal by pressing Cmd + Space, enter “Terminal” and open the application.
> 2. Run the following command: chmod +x /path/to/Application.app/Contents/MacOS/*. The path is case-sensitive and must point to the application bundle. (You can use Tab to complete file paths.)
>
> You only have to do this before starting the application for the first time. You can start the application as usual afterwards.
