### ISSUE TITLE
Black screen not working on android, Game version 0.8

### ISSUE THREAD

**Issue by Saikatsaha1996** [Libre-TrainSim/Libre-TrainSim#213]
Android 11
Snapdragon 865 processor
DDR5 8GB RAM
Game not opening showing black screen

**Comment by HaSa1002** [comment]
Is there a way to get a log file? Otherwise we can't do anything.
It is probably located somewhere where data is expected on Android. Sorry I don't use Android... I would guess there is too much to load, but idk.

**Comment by Saikatsaha1996** [comment]
Where I can get log file ? In Android app data folder ?

**Comment by DasCapschen** [comment]
Is the game not opening *at all*, or does it crash / show a black screen once you try to load a track?

**Comment by Saikatsaha1996** [comment]
Game opening, but shown black screen continue..

**Comment by HaSa1002** [comment]
> Where I can get log file ? In Android app data folder ?

Yes, probably.

**Comment by HaSa1002** [comment]
> Game opening, but shown black screen continue..

You don't even get to main menu, don't you?

**Comment by Saikatsaha1996** [comment]
No not getting main menu showing only black

**Comment by HaSa1002** [comment]
@Saikatsaha1996 could you please send us the log file? Without the file we can't do anything.

**Comment by Saikatsaha1996** [comment]
My android os version 11.. that's why I can't open/find my android data folder

**Comment by HaSa1002** [comment]
May this help? https://www.reddit.com/r/godot/comments/6pn9h2/getting_the_user_files_stored_in_android/

**Comment by Saikatsaha1996** [comment]
> May this help? https://www.reddit.com/r/godot/comments/6pn9h2/getting_the_user_files_stored_in_android/

You can't access android data folder after android os version 9.. with out root access..

**Comment by HaSa1002** [comment]
Ok. This is unsolvable then... Maybe there are ways to upload logs automagically to the Playstore backend or something like that.

**Comment by DasCapschen** [comment]
Apparently you can access logs with logcat over ADB. This is essentially like a console print out on classic linux. 
This does require enabling debug mode on your phone and connecting it with your PC, and installing android tools on your PC.

So if you can get that done, that would be great. https://developer.android.com/studio/command-line/logcat

You'll have to filter for LibreTrainSim, else you will see all kinds of spam in the log. The package name is `org.godotengine.libretrainsim`

If this is too hard for you, that's fine; we should get a developer to look into it instead.

**Comment by Saikatsaha1996** [comment]
Dear all!

I am happy to say Now game is working properly ☺️..
My device MI 10T
Ram DDR5 8gb 
Processor sdm 865
I am playing 30 minutes continue , no lag, no crash, no hit..

Game working fine.. thank you all for your work..
Best of luck!

My suggestion if possible!

Please add support to settings options
1) Like gpu , OpenCL acceleration, vulkan acceleration, OpenGL acceleration.. etc..

2) game optimization and add some more track side grass, more types of trees, and please change ground textures, and please add more coach and add more physics details..


Thank you

**Comment by HaSa1002** [comment]
Glad to hear. What did change?

> Like gpu , OpenCL acceleration, vulkan acceleration, OpenGL acceleration.. etc..

Well... you wouldn't see anything if we wouldn't use your GPU.

> game optimization

Sure, but it has to wait until we are building on top of a solid foundation. 0.9 will still be a duck-taped release. Let's see when that happens. There are some implications of our dev workflow and generally spoken: Mobile is s**** (IMO).

> add some more track side grass, more types of trees, and please change ground textures, and please add more coach and add more physics details..

Feel free to propose all those things in individual issues.

**Comment by nalquas** [comment]
I think this can be closed.

**Comment by Saikatsaha1996** [comment]
> I think this can be closed.

Yes it can be close.. but no updates available from long time in Android.. :/

**Comment by HaSa1002** [comment]
@Saikatsaha1996 Sadly, I can't do anything about it since Jean is the only person able to update the Android port of the game.

**Comment by Saikatsaha1996** [comment]
💔💔💔💔🥲🥲🥲

> @Saikatsaha1996 Sadly, I can't do anything about it since Jean is the only person able to update the Android port of the game.

**Comment by Saikatsaha1996** [comment]
Any windows 32bit program available?
