### ISSUE TITLE
Signal Tutorials and German Safety Tutorials broke with new chunk system

### ISSUE THREAD

**Issue by DasCapschen** [Libre-TrainSim/Libre-TrainSim#270]
Tutorials use relative paths, but stuff was moved around, so they broke. 
Should be an easy fix :)

**Comment by merspieler** [comment]
I've stumble upon this while packaging libre train sim for nixOS. Is there a fix in sight?

**Comment by DasCapschen** [comment]
This is a v0.9 issue. Are you packaging a beta or -git version?

I just see that this was moved to Milestone 1.0 at some point, which is why I completely lost track of this.  
This should get fixed for 0.9, if the issue is even still relevant.   
I won't be able to look into it until the 18th though.

**Comment by HaSa1002** [comment]
I don't even know why I moved it. Perhaps it has been an oversight while walking through the list. I may have time to it earilier if we need to release sooner than the 18th.

**Comment by merspieler** [comment]
Thanks for the quick reply.

I'm currently packaging a git version to get going but I'll probably wait for the next release before publishing the package.

**Comment by merspieler** [comment]
Thanks, works.
