### ISSUE TITLE
Language Submission (Bulgarian)

### ISSUE THREAD

**Issue by RacerBG** [Libre-TrainSim/Libre-TrainSim#272]
Hello everyone!

I like what I'm seeing so far in Libre TrainSim and I would love to watch how it evolves in the future. Having a FOSS train simulator around is great and I'm willing to make my contribution to it by translating it in to the Bulgarian language.

So far I had translated only the game, without the tutorial system. I will add the tutorials translation in another issue, probably after the release of version 0.9.

Keep up the good work and let's make the best free and open source train simulator!

Regards,
Georgi

Here are the translated files:
[Ingame.csv](https://github.com/Libre-TrainSim/Libre-TrainSim/files/7654229/Ingame.csv)
[JFR1.csv](https://github.com/Libre-TrainSim/Libre-TrainSim/files/7654230/JFR1.csv)
[MainMenu.csv](https://github.com/Libre-TrainSim/Libre-TrainSim/files/7739399/MainMenu.csv)
[authors_and_project.godot.zip](https://github.com/Libre-TrainSim/Libre-TrainSim/files/7739400/authors_and_project.godot.zip)

**Comment by HaSa1002** [comment]
Thank you very much :)

**Comment by RacerBG** [comment]
@HaSa1002 I had updated the MainMenu.csv file with the latest changes from the Scenario Editor and added the language information in the project.godot file and my name in the translators tab of the authors file to save you some work. :smiley: 

EDIT: I wonder if adding the "bg" string in "locale_filter" is needed because I added it anyway...

**Comment by HaSa1002** [comment]
Thank you very much for your contribution @RacerBG
