### ISSUE TITLE
Train goes through another train

### ISSUE THREAD

**Issue by sonjagerhard** [Libre-TrainSim/Libre-TrainSim#289]
I Played the Windows Version. I let the Autopilot Drive the train. At the Last Station another train Blockes our way. But train went through the Others train. One could See the seats of the Others Waggons.

*Edit: At Hainfurt Hbf*

**Comment by Jean28518** [comment]
Thank you very much!

**Comment by HaSa1002** [comment]
So you are not planning on fixing the issue for 0.9? I mean, you have to redo the scenarios anyway.

**Comment by Jean28518** [comment]
Closing this because we are redoing all scenarios for 0.9
