### ISSUE TITLE
Duplicate grass files

### ISSUE THREAD

**Issue by skyace65** [Libre-TrainSim/Libre-TrainSim#29]
There seems to be duplicates of grass files, they're the same except some files have an uppercase g. grass.mtl grass.obj and grass.obj.import

**Comment by Jean28518** [comment]
Thank you!
grass.obj is the object, grass.mtl is the material (which is unused at the moment), grass.obj.import ist the import data for godot. 
So everything okay :)
If you have further questions, just let me know ;)

**Comment by skyace65** [comment]
@Jean28518 Sorry, I should have been more specific. I know those files aren't duplicates of each other. But when cloning git says there's two of those files like `grass.obj` and `Grass.obj` where the only difference is the g. It doesn't show up online and I'm not sure why, but when cloning I get this issue.

warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'Resources/Basic/Grass.mtl'
  'Resources/Basic/grass.mtl'
  'Resources/Basic/Grass.obj'
  'Resources/Basic/grass.obj'
  'Resources/Basic/Grass.obj.import'
  'Resources/Basic/grass.obj.import'

**Comment by Jean28518** [comment]
Fixed with the latest commit :)

**Comment by skyace65** [comment]
Those files are fixed, but now I'm getting the same issue with .blend files

warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'Blender/Grass.blend'
  'Blender/grass.blend'
  'Blender/House1.blend'
  'Blender/house1.blend'
  'Blender/House1.blend1'
  'Blender/house1.blend1'
  'Blender/Platform.blend'
  'Blender/platform.blend'
  'Blender/Platform.blend1'
  'Blender/platform.blend1'

**Comment by Jean28518** [comment]
should be fixed :)

**Comment by skyace65** [comment]
It works perfectly now, thanks! I'll close this issue.
