### ISSUE TITLE
Feedback Button Error 404

### ISSUE THREAD

**Issue by sonjagerhard** [Libre-TrainSim/Libre-TrainSim#290]
https://www.libre-trainsim.de/feedback

In the Android Version the Button 
Feed Back
Ends Up in Error 404
The URL is copied above

**Comment by Jean28518** [comment]
Thank you very much! #284 will solve this

**Comment by HaSa1002** [comment]
Well. I do think this Issue is completely valid and is indeed not fixed yet. That is probably the only case where I didn't change the URL. Thus I am reopening it.

**Comment by HaSa1002** [comment]
Fixed in #298
