### ISSUE TITLE
Proposal see station

### ISSUE THREAD

**Issue by bodamat** [Libre-TrainSim/Libre-TrainSim#3]
- [x] Function for getting all signalpoints in right order of a specific type.
- [x] Calculate distance to a specific signal node
- [x] Display a Message, if the next station is only 1000 m away

I very like your game. Probably because it was created on Godot :)
Maybe need yellow light, before the station, because at high speed I didn't notice the station. It was as if the station had appeared before me. What do you think?

I do not know if I will be able to help, because I have not yet studied Godot to the end. I create only one small project. I know Unreal and create a project there. I wait Godot 4.0 :)
I can help you with translation to Ukrainian :)

**Comment by Jean28518** [comment]
Thank you very much for your offer!
I plan the the "See Station" feature follwing:
- 1000 m before you will get a message
- (The right screen will be a timetable soon)

**Comment by bodamat** [comment]
Very good plan. I will wait new updates :)
Do you plan to add phone support?
