### ISSUE TITLE
Evaluation in the end of the scenario.

### ISSUE THREAD

**Issue by Jean28518** [Libre-TrainSim/Libre-TrainSim#31]
That will let you measure, how well you drove the scenario ;)

**Comment by DasCapschen** [comment]
How exactly would this work? What things would factor into it?
I guess it would start with 100% and then subtract points when you do things wrong?
- going over the speed limit (I guess it should factor in how much and how long)
- leaving stations early
- arriving at stations late
- going over red signals (although, this just ends the game rightout, at the moment)
- not acknowledging SIFA (and in the future other safety measures)


For example in Train Simulator (Railworks): 
You start with 0 points.
Arriving at a station in time gives you 250 points.
If you go 72km/h in a 70km/h zone, you will lose 2 points every second until you have slowed to 70km/h or less. 

Something like that 🙂

**Comment by HaSa1002** [comment]
> (although, this just ends the game rightout, at the moment)

I just see a message 😅

**Comment by DasCapschen** [comment]
Well yeah, it just tells you that the game's over, although it's not. But you're locked into enforced braking, so nothing you can do really xD

**Comment by Jean28518** [comment]
I would sum up  `acknowledging SIFA (and in the future other safety measures) ` to `getting an enforced brake while driving`
