### ISSUE TITLE
AddOn Error while importing Assets

### ISSUE THREAD

**Issue by Jean28518** [Libre-TrainSim/Libre-TrainSim#312]
![grafik](https://user-images.githubusercontent.com/39700889/150637027-3500581a-1c01-41be-9ded-7f56ae416107.png)

Looks like a script error

Steps to reproduce:

Clone the current upstream repository and open it the first time with the newest godot version

**Comment by HaSa1002** [comment]
This is a Godot bug with loading the addons. There seems to be an issue with the load order. Just reenable the add-on

**Comment by Jean28518** [comment]
For what do we need this addon?

**Comment by HaSa1002** [comment]
Realistic Light Colours. As I said. Just enable the plugin. It works fine. That is a Godot Asset System bug
