### ISSUE TITLE
Bug: Import of .pck files doesn't work

### ISSUE THREAD

**Issue by Jean28518** [Libre-TrainSim/Libre-TrainSim#313]
![grafik](https://user-images.githubusercontent.com/39700889/150645479-b5342d15-c4a7-463f-bb6a-2dfd410db9ba.png)

How to reproduce:

content -> Import -> Select a .pck file

**Comment by HaSa1002** [comment]
That can't work anymore. Users need to extract zip files by themselves for 0.9. This can only be changed if we are going to implement a content browser. I am going to remove the button for 0.9
