### ISSUE TITLE
New .pck files in addons are not imported automatically

### ISSUE THREAD

**Issue by Jean28518** [Libre-TrainSim/Libre-TrainSim#314]
We should implement this for v0.9

**Comment by HaSa1002** [comment]
They are but you need a mod config

**Comment by Jean28518** [comment]
why can't we implement that mod config into the .pck file?

**Comment by DasCapschen** [comment]
Because to read a file from a pck, you need to load the pck, but then the mod is already loaded.

**Comment by Jean28518** [comment]
Okay, that's makes sense. Thank you!
