### ISSUE TITLE
Persons are running into nowhere on big maps

### ISSUE THREAD

**Issue by Jean28518** [Libre-TrainSim/Libre-TrainSim#326]
![image](https://user-images.githubusercontent.com/39700889/151391086-fcad55c3-e173-4c8a-b602-5b23a7736ecb.png)

I guess that the person handle where not updated for the new big chunk system

**Comment by DasCapschen** [comment]
I remember havin this issue and fixing it... I wonder why this happens again 🤔 
Does it always happen, or only in big chunks that aren't the (0,0,0) chunk?
