### ISSUE TITLE
Combined Signals are broken

### ISSUE THREAD

**Issue by DasCapschen** [Libre-TrainSim/Libre-TrainSim#337]
Combined Signals are currently broken and display *all* lights at once, instead of showing a specific state.
The non-combined variants of the signals still work as intended.

I give this low priority and assigned it to 1.0, because no maps currently use combined singals, so it is not a blocker for 0.9.  
Of course, user created content could run into this issue.

**Comment by HaSa1002** [comment]
Removed low prio label, as we should do priorisation differently. We can either hotfix later or just push it.

**Comment by DasCapschen** [comment]
I did not observe this issue any more... I guess we can close this 🤔
