### ISSUE TITLE
In-game feedback form URL is wrong

### ISSUE THREAD

**Issue by jpretori** [Libre-TrainSim/Libre-TrainSim#348]
When I finished playing the first "real" scenario (i.e. the first one I played that wasn't a tutorial).  The game asked me to give feedback.  When it opened the link in my web browser, I got a 404 error message - I suspect the trailing "/" is missing.

**Comment by HaSa1002** [comment]
Thanks for the report. This has been reported multiple times. It is should be only an issue in 0.8. We moved our webpage to libretrainsim.org.
Can you please tell me which version you are using?

Thanks :)

**Comment by RacerBG** [comment]
I don't know what is the current state of this button but this link ( https://libretrainsim.org/community ) located in Documentation/LibreTrainSim_Trains.md is wrong and should be corrected.

**Comment by jpretori** [comment]
> Thanks for the report. This has been reported multiple times. It is should be only an issue in 0.8. We moved our webpage to libretrainsim.org.
> Can you please tell me which version you are using?
> 
> Thanks :)

Sure enough, I'm on v0.8.
