### ISSUE TITLE
scons: *** No SConstruct file found.

### ISSUE THREAD

**Issue by tmanapat** [Libre-TrainSim/Libre-TrainSim#352]
Error message:
scons: *** No SConstruct file found.
File "/usr/lib/python3/dist-packages/SCons/Script/Main.py", line 947, in _main

Steps to reproduce:
OS Ubuntu 21.10

Forked/cloned repo.

~/Libre-TrainSim/src

Ran:
sudo apt-get install build-essential scons pkg-config libx11-dev libxcursor-dev libxinerama-dev     libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libudev-dev libxi-dev libxrandr-dev yasm

**Comment by DasCapschen** [comment]
Libre Train Sim is not built with scons, thus there is no SConstruct file.
You simply open the project you cloned in Godot Engine :)

**Comment by HaSa1002** [comment]
We should clarify the installation guidelines.
