### ISSUE TITLE
"Create a new mod" throws error when pressing OK

### ISSUE THREAD

**Issue by nalquas** [Libre-TrainSim/Libre-TrainSim#360]
### Summary
If you use "Create a new mod" in the Godot Editor and press OK, an error message is printed and nothing happens.

### How to reproduce
1. Open Libre-TrainSim in the Godot Editor.
2. Open the "LTS Modding" tab.
3. Click "Create a new mod".
4. Enter the required details (unique mod name, mod display name, author).
5. Press "OK".

### Observed behaviour
The following error message is thrown (in the output tab):
```
res://addons/libre_trainsim_modding_tools/new_mod_popup.gd:9 - Invalid call. Nonexistent function 'to_valid_filename' in base 'Node (Root.gd)'.
```

### Expected behaviour
A new mod is created.

**Comment by HaSa1002** [comment]
Yeah... Root.gd is called but it's not a tool script. It should probably moved into it's own `class_name`d script and turned into a static funtion just like the logger.
