### ISSUE TITLE
Rothenbach Station signal is not Red which lets you drive through wall

### ISSUE THREAD

**Issue by talmanau** [Libre-TrainSim/Libre-TrainSim#368]
Signal at Rothenbach Station was Orange which let me drive to the end of line. There was a Red signal at the wall but this still allows you with the train's momentum to drive through the end of line wall.

**Comment by HaSa1002** [comment]
That is 0.8 Nuremberg, correct? IIRC this has been addressed by @DasCapschen for 0.9

**Comment by talmanau** [comment]
Yes this was the 0.8 version for Windows

**Comment by HaSa1002** [comment]
fixed in v0.9 (https://github.com/Libre-TrainSim/u2-nuremberg/commit/b3a45a7d88ab38ed98f6649d9ffb24d96ba8500f)
