### ISSUE TITLE
Language Update Submission (Spanish)

### ISSUE THREAD

**Issue by Pablo-Lilao** [Libre-TrainSim/Libre-TrainSim#377]
I completed the MainMenu.csv and I fully translated German-Safety-Tutorials.csv

[German-Safety-Tutorials.csv](https://github.com/Libre-TrainSim/Libre-TrainSim/files/9077577/German-Safety-Tutorials.csv)
[MainMenu.csv](https://github.com/Libre-TrainSim/Libre-TrainSim/files/9077578/MainMenu.csv)

**Comment by Pablo-Lilao** [comment]
Update: Actually I translated everything. I tried to use professional railway jargon.
[Signal-Tutorial.csv](https://github.com/Libre-TrainSim/Libre-TrainSim/files/9078535/Signal-Tutorial.csv)
[Tutorials.csv](https://github.com/Libre-TrainSim/Libre-TrainSim/files/9078537/Tutorials.csv)
[Ingame.csv](https://github.com/Libre-TrainSim/Libre-TrainSim/files/9078538/Ingame.csv)
[German-Safety-Tutorials.csv](https://github.com/Libre-TrainSim/Libre-TrainSim/files/9078539/German-Safety-Tutorials.csv)
[MainMenu.csv](https://github.com/Libre-TrainSim/Libre-TrainSim/files/9078540/MainMenu.csv)

**Comment by HaSa1002** [comment]
Thank you ❤️

**Comment by Pablo-Lilao** [comment]
You're welcome. Just keep the good work :)

I was a programmer for some years and now I'm a train driver (or however it is said in english). I love FOSS and I was thinking on doing a train simulator myself but then I discovered this project. I would love to contribute more in the future but now I don't have the time/means
