### ISSUE TITLE
Catenary in editor does not follow rail curves

### ISSUE THREAD

**Issue by Pablo-Lilao** [Libre-TrainSim/Libre-TrainSim#378]
I made a rail curve in editor v0.8 and the catenary builds itself from the start of the rail to the end in straight line, not following the track curve.

In Spain not all the tracks have electricity. Is possible to make a track without catenary?

![catenary-straight-on-curve](https://user-images.githubusercontent.com/63185445/178142803-4fa518a6-45a4-4943-a501-e9ea00e67bef.png)
![catenary-straight-on-curve-2](https://user-images.githubusercontent.com/63185445/178142811-3f0fb691-fee0-467e-b479-8ef75b2e6729.png)

**Comment by DasCapschen** [comment]
I think this is fixed in v0.9, right @HaSa1002 ? 
And powerlines can be disabled in the v0.9 editor :)

**Comment by HaSa1002** [comment]
Yeah well "fixed". You have to tweek the distance between poles to achieve a good curve. Nothing automagic, though. I'd keep this Issue as UX issue.

**Comment by Jean28518** [comment]
This feature is added into v0.9
