### ISSUE TITLE
Free outside camera view rotation broken

### ISSUE THREAD

**Issue by nalquas** [Libre-TrainSim/Libre-TrainSim#385]
### Summary
Camera rotation in external view is completely broken.

### How to reproduce
1. Start the game and enter a train...
2. Press "0" to go to free camera
3. Try to rotate the view (using mouse movement)

### Observed behavior
The camera spins out of control.

### Expected behavior
The view is rotated according to my mouse movement.

### Version
 - Game Version: commit 511bce3dde41ab665cbf9926b959ddf063ebba6f
 - OS: Linux

### Additional information
Bug appeared after https://github.com/Libre-TrainSim/Libre-TrainSim/pull/277 was merged.

Before (at 1724aa7a288c5602ba2546577c6ddf0af11a9490):

https://user-images.githubusercontent.com/22664233/185753185-9b28e9de-ebb9-4648-bd3d-a0431e3c1bc3.mp4

After (at 511bce3dde41ab665cbf9926b959ddf063ebba6f):

https://user-images.githubusercontent.com/22664233/185753226-d1d560d3-d814-49d2-a462-24595471b74c.mp4

**Comment by HaSa1002** [comment]
Unlucky. This should be fixed by refactoring the camera out of the player script using a new camera based on camera_base.gd. It probably needs some signals in the player script.
