### ISSUE TITLE
Track Editor: Saving makes all tracks invisible

### ISSUE THREAD

**Issue by nalquas** [Libre-TrainSim/Libre-TrainSim#388]
### Summary
In the track editor, pressing "Save World" or using `Ctrl+S` makes all tracks go invisible.

### How to reproduce
1. Open any track in the track editor
2. Save (Using "Save World" or `Ctrl+S`)

### Observed behavior
All tracks go invisible, although the direction indicators (the red/green arrows and the white one in the middle) stay visible.
Clicking one of these indicators makes its track piece appear again.

### Expected behavior
The world is saved and the tracks stay visible.

### Version
 - Game Version: commit 64586c1c80c69a66a153bbc886966ca34dea00a5
 - OS: Linux

### Additional information
Returning to menu and opening the track again makes the tracks go visible again.
Bug appeared after https://github.com/Libre-TrainSim/Libre-TrainSim/pull/277 was merged.

**Comment by DasCapschen** [comment]
I believe this is a chunk issue.  
If you enable `load_all_chunks` in Project Settings, the issue disappears.

I am currently rebasing #236, so hopefully the new chunk system will fix it :)
