### ISSUE TITLE
Track Editor: Dragging rail into sky crashes game

### ISSUE THREAD

**Issue by nalquas** [Libre-TrainSim/Libre-TrainSim#395]
### Summary
Dragging a rail into the sky crashes the game.

### How to reproduce
1. Open any track in the track editor.
2. Find a rail somewhere.
3. Drag the end of the rail into the sky. You might have to angle the camera a bit to do this.

### Observed behavior
The game crashes with the following error:
`Trying to assign value of type 'Nil' to a variable of type 'Vector3'.` at `res://Editor/Scripts/Editor.gd:73 - at function: handle_drag_mode`.

### Expected behavior
Nothing happens (or the action is canceled), or an error is shown.

### Version
 - Game Version: Commit a5ceb0efdf26b0f0df4005299e31f68ef4b4c307
 - OS: Linux

### Additional information
Video of the bug in action:

https://user-images.githubusercontent.com/22664233/186263389-9c9b2dde-f04a-4c3c-9f5a-c35b83fb4dd0.mp4

**Comment by HaSa1002** [comment]
Yeah makes sense. This needs an additional check and we should simply use the last propper value.

**Comment by Jean28518** [comment]
Do we want to fix this in the 0.9?
In my whole track building of about 50 km track I didn't recognized it.
