### ISSUE TITLE
Remove globalDict from World

### ISSUE THREAD

**Issue by DasCapschen** [Libre-TrainSim/Libre-TrainSim#400]
World contains a variable `var globalDict := {} ## Used, if some nodes need to communicate globally. Modders could use it. Please make sure, that you pick an unique key_name`

It is used in a few places, but we should remove it and replace it with a better solution if necessary.

**Comment by nalquas** [comment]
It appears the only remaining use for `globalDict` is `Data/Screens/ScreenSpeedometer/screen_speedometer.gd`. It seems to be used for blinking status synchronization between the ingame screen and the GUI overlay.
