### ISSUE TITLE
SiFa not working

### ISSUE THREAD

**Issue by nalquas** [Libre-TrainSim/Libre-TrainSim#410]
### Summary
The SiFa system doesn't appear to be online, no matter the setting. It only works in the SiFa tutorial.

### How to reproduce
1. Open a map, for example "Tutorials/Free Driving", in advanced mode.
2. Drive for a while.
3. Notice that the SiFa warning never appears.

### Observed behavior
The SiFa feature doesn't seem to be working. You can drive the train without ever needing to press 'Space'.

### Expected behavior
After 30 seconds of driving in advanced mode, the SiFa system applies emergency brakes. It also audibly warns you a few seconds before. Pressing 'Space' resets the timer.

### Version
 - Game Version: commit 25ed03acb353fe4ef882ddaa844d8fcb32c0c58a

### Additional information
I'm not sure when this broke. It worked way back in 0.8.
It's still working in the "German-Safety-Tutorials/SiFa" scenario.

**Comment by DasCapschen** [comment]
I found the issue. Sifa and PZB broke when we changed how the settings are saved.  
SiFa Module still uses `jSaveManager`, but we use `ProjectSettings` now :)

I will create a merge request to fix it.

**Comment by DasCapschen** [comment]
By the way, if you ever need to Debug Sifa, you can go to `res://Data/Modules/SifaModule.tscn` and in the scene make the `DEBUG` node visible. It gives you an on-screen HUD about what the system is doing.  
Same goes for PZB :)
