### ISSUE TITLE
Reinventing Track-File:

### ISSUE THREAD

**Issue by Jean28518** [Libre-TrainSim/Libre-TrainSim#42]
Instead of a tscn File, only a .cfg file should be used for tracks. So with that loading time could be decreased a lot. Also it won't take so much Disk-Space anymore

**Comment by comick** [comment]
@Jean28518 what do you have in mind when talking about cfg file? Some sort of more compact custom text representation of World scene to be parsed and leaded via script?

**Comment by Jean28518** [comment]
In the .cfg file only the Information about positions, materials and types, and seeds (for forests...) will be saved.
Actual the transformation of every single MultiMeshInstance is saved. That takes a lot of disk space, and slows down the loading of the track.

With it an Ingame Editor should come.. But for now that's future ;)

**Comment by comick** [comment]
Is the issue with space and loading something for editing only? When exporting a scene, godot uses scn format which is a binary packed version of the human readable toml version. At least at runtime things should be good enough if I understood correctly.

**Comment by Jean28518** [comment]
No, the loading time at runtime is lto long. Because at loading the whole track is loaded into the world. In the first second, then everything is unloaded, which we don't need to our time. So very long tracks are not possible with this method.

In the end I don't want to have a packed .scn file of the track. Just a "generic" World scene, in which then every elements of the .cfg are loaded in. 
Do you understand?

**Comment by comick** [comment]
What is done in geospatial is to "tile" the world and load tiles based on proximity. Is that what you had in mind?
Other than a "generic" worlds scene, which would be some custom file format, what about a post processing of the very godot scene that splits bigger scenes into fixed size chunks along the track line and loaded based on camera proximity and rendering distance?
Scene file format is quite straightforward and you would keep tracks fully editable in Godot, which is great value.

**Comment by Jean28518** [comment]
The world already has a fully working self developed chunk system, which is based on proximity. There even exists a file, which saves the almost all objects in chunks of 1000m*1000m. 
The chunks are loaded based on the players train position.

The problem with the whole scene file format in godot: If a scene is loaded, the whole track in it will be loaded in. For tracks more than 30 km this editing becomes very unhandy.

The converting from a .scn to our .cfg file shouldn't be the problem.
The major problem is, how to edit very long tracks in godot itself, because the godot editor is not friendly, when you want to enhance it, and change behaviours. 

For an ingame editor you have much work in the beginning, but in the end we have the full control over it, and could develop and design it, how we want. Also the accessibility for new track creators would be awesome. I think I will open a new issue about the Editor Future.

**Comment by Jean28518** [comment]
-> #50

**Comment by Jean28518** [comment]
The .tscn file exists further on, but an unload button was now added. So for exporting track, the .tscn file size doesn't get a whole MB instead of hundrets.
