### ISSUE TITLE
Objects as TSCN, not Mesh

### ISSUE THREAD

**Issue by DasCapschen** [Libre-TrainSim/Libre-TrainSim#421]
### Summary
When adding Objects to the Scene, you currently have to select the Mesh from a list and then apply materials 1-by-1 per surface.  
It would be nicer to select the finished object from a thumbnailed list.

### Proposal
Objects should be "prefabs". That is, pre-configured scenes (e.g. a MeshInstance) with already assigned materials.  
The user should not be allowed to select materials.  
Instead, if multiple variants using the same Object / Mesh are needed, multiple "prefabs" should be created with the same mesh but different materials assigned.  
This will also allow Thumbnails (Godot can already generate thumbnails for tscn files, perhaps we can somehow use this)

**Comment by HaSa1002** [comment]
Yeah I started doing it, then realised how many objects we have, took a look at my calendar, and decided to build the material name feature. xD
I'd also advocate to group prefab variants if you wish as well as assigning them tags to ease the UI.

**Comment by HaSa1002** [comment]
# Concept

I made a small concept thinking about the required features and how to visualise them. Feel free to throw in some more thoughts as I am sure, I forgot some usages.

## Requirements/Features

1. Select multiple objects: Placed object is randomly chosen for each click
2. Genric filters like buildings, vegetation etc. **What do we need? (See some ideas below)**
3. Specific groups to visually group objects
4. Selection of group, toggles list of groups
5. Selection of random button next to the group name selects all objects of that group
6. Shader has a colour tint variable (which can be randomised)
7. Allow reference of custom “editor” in object resource
8. Allow marking of objects as favourites
9. Count usage in scales and propose them in a “Recently/Commonly used” section
10. Tint Colour can be selected using a colour wheel (Godot default) and by using a colour palette
11. Selected objects stick to the cursor.
12. Placed objects are respawned.
13. A search bar

## Generic Filters

1. Buildings
2. Vegetation
3. Infrastructure
4. Human Interactable/Small Scale Objects -> decorative
5. Favourites
6. Most Commonly Used
7. Most Recently Used

I am not so super happy with them. What are you actually using most of the time?

## Wireframes

![grafik](https://user-images.githubusercontent.com/14185889/192109215-82f1c875-30b9-4013-abc0-632106d824be.png)
![grafik](https://user-images.githubusercontent.com/14185889/192109248-27ec2de2-63d5-4c2f-b603-b1364ced689d.png)

The green squares extend on hover to show the name of the filter. They can be toggled and have different colours for the different stages. The yellow square is a placeholder for a *favourite marker*. The dark grey square shows the icon or thumbnail of the object. The box below the the thumbnail shows the name of the object. The cyan coloured box defines the tint colour and is a colour picker button.

I also replaced the "+"-button with the entries it grouped.

**Comment by HaSa1002** [comment]
Another update on the colours:
I want to add a colour palette to enable colour randomisation that is actually useful and to speed up the tinting workflow. We may wanna provide some default palettes.
Here's a new mockup/wireframe:
![grafik](https://user-images.githubusercontent.com/14185889/194782338-d570217c-b2f7-47da-be9c-1365ca9d8ee5.png)

Description of the colour palette features:
1. Support for up to 24(?) colours -> verify good number
2. Multiple colours can be selected
3. Next colour is randomisable (green button)
4. Menu Button lists all “installed” colour palettes
5. Hovering over a palette shows the palette
6. Creating a new palette opens the modal window
7. Usage of default Godot colour picker
8. Showcase of the added colours
9. Each colour is put into the text field in hex
10. Edits of the text field are immediately parsed

**Comment by DasCapschen** [comment]
Instead of cross-posting, could you perhaps instead just link to the comment in the PR?  
I really don't want to manage a discussion about 1 thing in 2 places.
