### ISSUE TITLE
Weird loading of near chunks

### ISSUE THREAD

**Issue by Jean28518** [Libre-TrainSim/Libre-TrainSim#439]
### Summary
very near chunks aren't loaded. Maybe there is an error in get_chunk_neighbours() or in position to chunk translation

### How to reproduce
1. Open Hainfurt.tscn,
2. Jump to station Ostkurve, fly in direction of buchenhain. (If this chunk is currently loaded, just press ctrl + s)

https://user-images.githubusercontent.com/39700889/204140983-1fb102dd-a1b1-499a-8fdd-2184133cf7d2.mp4

**Comment by Jean28518** [comment]
If someone asks, yes the rail attachements are stored in the right chunk (`18_8`)

**Comment by Jean28518** [comment]
Can't reproduce this anymore at the moment.

**Comment by HaSa1002** [comment]
Closing as not reproducable
