### ISSUE TITLE
Crash: "Test track" and "Export Track" in scenario editor

### ISSUE THREAD

**Issue by Jomosoto** [Libre-TrainSim/Libre-TrainSim#456]
Platform: Linux x86_64

When you click on "Test track" or "Export Track" in the scenario editor pause menu the game get's terminated by a SIGSEGV signal.

When clicking these buttons inside the godot editor the game freezes and uses more and more memory.

**Comment by HaSa1002** [comment]
Can't reproduce on Windows. Can you please upload your map? With it I can verify the issue is indeed multiplatform and not linux only 😬

**Comment by nalquas** [comment]
Tested on Linux x86_64 using current master branch (5eff94e140650724d326f32f4ec4121550353e13). Can't reproduce.

**Comment by Jomosoto** [comment]
I did some tests: It happens when trying to edit a scenario of one of the tutorial tracks, but not in track-editor maps (I tried Hainfurt)

**Comment by Jomosoto** [comment]
The problem is, that the built-in maps are inside of res:// (which is read only of course) and the game tries to save it to that location. I think you just shouldn't be able to edit the scenarios of the built-in maps. (Or is this a wanted feature?)

**Comment by HaSa1002** [comment]
I think Jean intended this as feature
