### ISSUE TITLE
Input is queuing after a while

### ISSUE THREAD

**Issue by comick** [Libre-TrainSim/Libre-TrainSim#46]
After some time playing (driving train), input is not responsive anymore and keeps delaying showing sort of queue effect:
input keys are taken, but their effect is increasingly delayed.

The problem reproduces on both released 0.6 (JRF1 on any track) and latest master (0.7 still JFR1 on any track).
From the code (looked into Player.gd) I could not find an obvious point where input is queued.
FPS are not degrading when this happen, just input happens to be processed later.

**Comment by comick** [comment]
I'm using Linux with Intel integrated video i915. The internet suggests many users have this kind of problem with godot games and godot editor itself.

**Comment by comick** [comment]
Same issue on Linux with discrete card using driver radeon (r600).

**Comment by Jean28518** [comment]
Yeah, I had this issue with gnome3.
With Xfce or Cinnamon I don't have such problems.
Maybe wayland is the cause...
Which desktop do you use?

**Comment by comick** [comment]
Made some more research upon your feedback. It turns out the problem was ibus messing with input.
Gnome itself works also without on wayland without problems.
Have to either `ibus stop` or `apt autoremove --purge ibus`.

Don't think this is a bug with the game. Thanks for supporting!
