### ISSUE TITLE
PZBMagnet is not recognised

### ISSUE THREAD

**Issue by HaSa1002** [Libre-TrainSim/Libre-TrainSim#460]
### Summary
PZB magnets don't seem to be detected. I feel like there may be a deeper bug?

```
[2023-01-29 01:16:22][INFO](Null) Player: SIGNAL: PZBMagnet6
 [2023-01-29 01:16:22][ERROR](Player:[Spatial:30496]) Unrecognised signal type PZBMagnet passed
	At: res://Data/Scripts/Player.gd:837:handle_signal()
	At: res://Data/Scripts/Player.gd:749:check_signals()
	At: res://Data/Scripts/Player.gd:342:_process()
```

### How to reproduce
1. Run the PZB tutorial
2. Observe the console.

### Observed behavior
```
[2023-01-29 01:16:22][INFO](Null) Player: SIGNAL: PZBMagnet6
 [2023-01-29 01:16:22][ERROR](Player:[Spatial:30496]) Unrecognised signal type PZBMagnet passed
	At: res://Data/Scripts/Player.gd:837:handle_signal()
	At: res://Data/Scripts/Player.gd:749:check_signals()
	At: res://Data/Scripts/Player.gd:342:_process()
```

### Expected behavior
Yeah nothing really.
```
[2023-01-29 01:16:22][INFO](Null) Player: SIGNAL: PZBMagnet6
```
### Version
 - Game Version: 0.9 (#462 )
 - OS: Windows

**Comment by Jomosoto** [comment]
When the signal type is checked, the error is printed before the signal is checked for the PZB types (The PZB module does it via the signal)

https://github.com/Libre-TrainSim/Libre-TrainSim/blob/75dcd4083c13554238ae1ec6fe7a79cd305fbbe1/src/Data/Scripts/Player.gd#L835-L847

There's no gameplay bug, but the error should not be printed in this case
