### ISSUE TITLE
Tutorial messages break PZB Screen

### ISSUE THREAD

**Issue by DasCapschen** [Libre-TrainSim/Libre-TrainSim#477]
### Summary

1. The PZB screen is still animated when Pause mode is on (e.g. a tutorial message is open)
2. If in restrictive mode, it will blink when pause mode is on, but it will stop blinking when closing the tutorial message

### How to reproduce

1. play the PZB tutorial
2. stop before the red signal
3. observe the pzb screen break once the tutorial popup for restrictive mode opens

### Version

- Game Version: master
- OS: linux

**Comment by Jomosoto** [comment]
Found the problem: Every frame it is checked if the train speed is zero, so every frame the restrictive mode is started if the speed is zero. So the blink timer is restarted at 0.5 seconds every frame, except when pause mode is on, then the PZB module is paused. I can try to fix this.
