### ISSUE TITLE
Message text changed when opening settings ingame

### ISSUE THREAD

**Issue by Jomosoto** [Libre-TrainSim/Libre-TrainSim#482]
### Summary

When opening the settings ingame in the pause menu while a message is open, the text of the message is changed to "Test Test meine Freunde"

### How to reproduce

1. Start any scenario
2. Play until a message is shown
3. Go into the pause menu and open the settings
4. Close the settings
5. See the error

### Version

- Game Version: master (at 4131179)
- OS: Artix Linux x86_64

**Comment by nalquas** [comment]
Confirmed and reproduced. This probably has something to do with the translation being refreshed/changed when the settings menu is closed.

(tested on 413117976bc611ee584e660cd210eba104f61c88 using Manjaro Linux x86_64)

![Screenshot_20230225_181232](https://user-images.githubusercontent.com/22664233/221597886-8c880225-a44e-45e3-93d3-f2cec7af893e.png)
