### ISSUE TITLE
Feasibility for generating maps from open street map

### ISSUE THREAD

**Issue by merspieler** [Libre-TrainSim/Libre-TrainSim#483]
I'm a huge fan of this sim and can't wait for the 0.9 release to be ready.
What I'm missing are real world tracks... and many to pick from.
For [flightgear](https://flightgear.org) I've generated scenery based on open street map data.
Would this be somewhat easily doable with the already available tooling or would I have to build a full tool chain for that?
If it's the first, could you please describe how (also maybe considering elevation... I've already got SRTM sources at hand)

Also, if it makes things easier, I'm happy to chat over on matrix about this.

**Comment by DasCapschen** [comment]
There are already 2 issues about this.  

- https://github.com/Libre-TrainSim/Libre-TrainSim/issues/424  
I've already started building a workflow in QGIS to postprocess OSM data, but it is not ready to use.  
Getting the vectors and getting SRTM data and applying the SRTM elevation to the vector points is rather easy.  
The tricky part is converting the Vector lines (which are sometimes poly lines, sometimes beziers, sometimes arcs) into only straight lines and arcs. (if you don't, you'll have curves built out of many small straight pieces)

- https://github.com/Libre-TrainSim/Libre-TrainSim/issues/480  
This user already imported tracks from OSM vectors, but is missing the curvature, just like i described above.
