### ISSUE TITLE
Train choice is ignored

### ISSUE THREAD

**Issue by nalquas** [Libre-TrainSim/Libre-TrainSim#484]
### Summary

When choosing another train than the default for a track/route, the player's choice is ignored and the default used anyway.

### How to reproduce

1. Click 'Play'
2. Select a map (e.g. 'Tutorials')
3. Select a scenario (e.g. 'Free Driving')
4. Select another train than the default (such as 'JFR1_Grey')
5. Click 'Play'
6. Go to exterior view (press '2') and look at the train

### Observed behavior

The default train has been loaded. For the above example (Tutorials/Free Driving), you'll see the red train.

### Expected behavior

The player's selected train has been loaded. For the above example (Tutorials/Free Driving), this should be the grey train.

### Version

- Game Version: current master (413117976bc611ee584e660cd210eba104f61c88)

**Comment by DasCapschen** [comment]
Can you try a different scenario that is not a Tutorial? 
The tutorial might force the red train.

**Comment by nalquas** [comment]
> Can you try a different scenario that is not a Tutorial? The tutorial might force the red train.

I also tried U2-Nuremberg (where grey is the default, so I selected red) and I still got the default (grey in this case) train.

**Comment by nalquas** [comment]
Oh wow, the player selection is only applied if a route doesn't set a default train. I'll make a fix PR shortly...
