### ISSUE TITLE
High VRAM usage

### ISSUE THREAD

**Issue by nalquas** [Libre-TrainSim/Libre-TrainSim#486]
### Summary

The game currently uses way too much VRAM, maxing out most consumer GPUs on our current maps (U2_Nuremberg / Hainfurt).

### Some ideas

I suspect the game stores each instance of each loaded resource in VRAM. There's a **lot** of redundancy there, and we can probably fix this. It would likely require significant code refactoring/rewriting, though.

Someone will have to do a deep-dive into our codebase and figure out where and why resources are loaded redundantly, and then come up with a more efficient way of doing it.

There's probably a tool for looking at what's using up VRAM in Godot. That could help us narrow down the issue. For example, there's an integrated 'Video RAM' monitor in Godot's debugger, and you can export the data into a text file. I've also tried [Govira](https://gitlab.com/monnef/govira) for this before, which is a VRAM usage analyzer that takes the Godot debugger's exported text file as input.

### Alternatives

None if there are larger / more detailed maps to come...

We will have to address this sooner or later, and the longer we wait, the more difficult it will become to solve.

### More details

My system:

- I'm using a GTX 1060 6GB. U2_Nuremberg just barely fits in there and works fine, but Hainfurt is unplayable.
- I'm on Linux, but have observed the issue on Windows as well.

The issue has been noticed several times already. Some examples:

- https://github.com/Libre-TrainSim/hainfurt/pull/4#issuecomment-1242978308
- https://github.com/Libre-TrainSim/Libre-TrainSim/issues/98
- Probably this one too, since Android phones have little VRAM: https://github.com/Libre-TrainSim/Libre-TrainSim/issues/213#issue-1045799004

**Comment by nalquas** [comment]
> For example, there's an integrated 'Video RAM' monitor in Godot's debugger, and you can export the data into a text file.

Some additional details on how to use the debugger remotely with an exported build:

1. Start the Godot Editor directly from the command line like this: `godot -e --path /absolute/path/to/Libre-TrainSim/Libre-TrainSim/src --debug-server 127.0.0.1:6007`.
2. Start the exported (debug) build of Libre-TrainSim from the command line like this: `./Libre_TrainSim.x86_64 --remote-debug YOUR_LOCAL_IP_ADDRESS:6007`.

You should now have a working remote debugger in the Godot editor. Please note that this doesn't survive game restarts, so you'll have to close the Godot Editor between game launches.

**Comment by nalquas** [comment]
Unfortunately, the VRAM monitor shows significantly less used VRAM than is actually used. We'll have to investigate this further, but for now, here's some exported VRAM overview files from the Godot Debugger:

- [libre-train-sim-vram-u2nuremberg.csv](https://github.com/Libre-TrainSim/Libre-TrainSim/files/10831978/libre-train-sim-vram-u2nuremberg.csv) (U2-Nuremberg track)
- [libre-train-sim-vram-tutorial-free-drive.csv](https://github.com/Libre-TrainSim/Libre-TrainSim/files/10831989/libre-train-sim-vram-tutorial-free-drive.csv) (Tutorial track in Free Driving scenario)

(I set my graphics settings to minimum for this, a.k.a. dynamic lights off, shadows off, AA off)

**Comment by nalquas** [comment]
This Godot Docs page has some tips that might apply to us:

- https://docs.godotengine.org/en/3.1/tutorials/3d/3d_performance_and_limitations.html#rendering

The most important point is to reuse materials and shaders, which I think is exactly what we need to do.

**Comment by HaSa1002** [comment]
I don't think materials are the problem. Nor a shaders. They are visually bad already and reused in places where they shouldn't. Quite the contrary, we should aim to improve the assets. @DasCapschen suggested the catenary being a culprit, as they are unique per rail. But there may be other improvements required to ensure asset instances are saved instead of copies.

**Comment by HaSa1002** [comment]
I found the culprit: The signals are the issue. Something goes terribly wrong there. if you don't load the visual instance here, there's no VRAM issue at all and everything looks like it should be.
https://github.com/Libre-TrainSim/Libre-TrainSim/blob/413117976bc611ee584e660cd210eba104f61c88/src/Data/Scripts/Signal.gd#L56-L63

CC @DasCapschen

**Comment by HaSa1002** [comment]
I think the issue are the dynamic speed textures. (At least removing them in the Ks signal fixes the issue) I feel like we need to add a custom cache for them. Godot simply can't cache them as they are generated at run-time and the signals are always visible. Alternately they could only be shown when they're actually visible

**Comment by HaSa1002** [comment]
Also moving this to 0.9 as it was introduced in this release cycle.

**Comment by nalquas** [comment]
> I think the issue are the dynamic speed textures. (At least removing them in the Ks signal fixes the issue) I feel like we need to add a custom cache for them. Godot simply can't cache them as they are generated at run-time and the signals are always visible. 

Why don't we just use Label3D to show speed limits?

**Comment by HaSa1002** [comment]
They didn't exist back then :P
