### ISSUE TITLE
Passengers walk through closed doors when wrong doors are open

### ISSUE THREAD

**Issue by Jomosoto** [Libre-TrainSim/Libre-TrainSim#500]
### Summary

It doesn't matter which doors are open, if the doors on any side are open the passengers enter and leave the train. If you open the doors on the wrong side, the people just walk through the closed doors

### How to reproduce

1. Start any scenario with a station
2. Close the doors and open them on the wrong side
3. Watch the passengers walk through the closed doors

### Version

- Game Version: master (at 292bf45e9d1f587795ad442bd3d1c1a0b9a78d8f)
- OS: Artix Linux x86_64

**Comment by nalquas** [comment]
Reproduced and confirmed.
