### ISSUE TITLE
Adding Persons in Libre TrainSim

### ISSUE THREAD

**Issue by Jean28518** [Libre-TrainSim/Libre-TrainSim#51]
- [x] Modular Way System 
- [x]  Persons with basic navigation
- [x] Portal System between Platform and train
- [x] Seat Areas In Train
- [x] Wagon counts passengers
- [x] 5 different passengers with animation
- [x] Adjustable Person Count per Station
- [x] Entrance of Persons
- [x] Leaving of Persons

**Comment by bodamat** [comment]
Hi! I can help you with different people models :) I or you can take it from mixamo :)

**Comment by Jean28518** [comment]
Thanks!
If the license allows it, that would be great.

**Comment by bodamat** [comment]
Yes. Adobe Mixamo allows us to use it for free for personal, commercial, and non-profit projects. I'll do it when I have time. Can you tell, what animation states we need?

**Comment by Jean28518** [comment]
Thanks.
- Sitting
- Standing
- Walking
- (Walking over Stairs upwards)
- (Walking over Stairs downwards)

**Comment by Jean28518** [comment]
Hey :) @bodamat Did you create some people models and/or animations?

**Comment by bodamat** [comment]
> Hey :) @bodamat Did you create some people models and/or animations?
> 
> 

I didn't create it :) I just took them from mixamo, but I have different problems to do what I want :) So I decided to mix all animation to each model in blender and import to godot. 
Before I wanted to import all animations and assign it to each character model, but it didn't work as expected.

**Comment by comick** [comment]
@Jean28518 I pulled latest master and noticed that some resource is missing at `res://Resources/Basic/Persons/Human1.tscn` which leads to null reference when populating the platform with people. Is that an artifact from development and the Human1.tscn is missing?

**Comment by Jean28518** [comment]
Oh sorry! Try it now :)
