### ISSUE TITLE
Concercn regarding railroad switches

### ISSUE THREAD

**Issue by andreanardin05** [Libre-TrainSim/Libre-TrainSim#516]
Hello, I am writing this to request about whether it was possible to incorporate railroad switches on my railway network, and if so I was wondering how can I do it and whether it was possible to control them afterwards.
Thank you in advance for your time, I will wait patiently for your reply.

**Comment by Jomosoto** [comment]
You can create switches in the track editor by adding two rails after the preceding rail:

https://github.com/Libre-TrainSim/Libre-TrainSim/assets/40580158/b944c762-0fc6-4c44-83bf-bb42430f8f45

At the moment the train will automatically pick the correct rail to reach the next station and you can't control switches ingame, but this feature may be implemented in the future. You can follow the developement here: https://github.com/Libre-TrainSim/Libre-TrainSim/issues/94
