### ISSUE TITLE
Chunk loader loads and unloads unnecessary chunks at the corners of surrounding area. Broken get_chunks

### ISSUE THREAD

**Issue by custodian** [Libre-TrainSim/Libre-TrainSim#523]
### How to reproduce

I. Unnecessary chunks

1. Set Game / Gameplay / View distance to 10000 & or disable fog
2. Load any world
3. Zoom out
Video 1

II. Broken `get_chunks`
1. Set Game / Gameplay / View distance to 10000 & or disable fog
2. Set Game / Gameplay / Chunk Load Distance to 6
3. Load any world
4. Zoom out
Image 2

### Observed behavior

Extra chunks loaded right now, later they will be unloaded, and the loaded once again

### Expected behavior

No extra chunks at the corners
All surrounding chunks properly loaded

### Version

- Game Version: master

### Additional information

Video 1
https://github.com/Libre-TrainSim/Libre-TrainSim/assets/935667/a565c61a-2702-45d3-b23c-75548a63a3db

Image 2
![image](https://github.com/Libre-TrainSim/Libre-TrainSim/assets/935667/47949d45-8709-4a8b-8c85-c769a42c838a)

**Comment by HaSa1002** [comment]
CC @DasCapschen
