### ISSUE TITLE
Assertion fails upon opening newly created map in track editor

### ISSUE THREAD

**Issue by nalquas** [Libre-TrainSim/Libre-TrainSim#530]
### Summary

When creating a new track and trying to open it in the track editor, an assertion fails.

### How to reproduce

1. Create a new track ("Create" → "Track Editor" → enter some name → "New")
2. Select the track and press "Open"
3. Observe

### Observed behavior

As loading reaches 100%, the game halts due to a failed assertion with the following output:

![Screenshot_20230819_231449](https://github.com/Libre-TrainSim/Libre-TrainSim/assets/22664233/78b6b0a9-38be-4abe-9f97-1ec8ec868a1f)

Restarting Libre-TrainSim and opening the track again fixes the map, but shows a message "World was converted to v2 chunks. Please reload the world".

### Expected behavior

The track loads fine.

### Version

- Game Version: Current master (commit 3952171a8222b2f1f2a48b16adf946769ac1ae35)

### Additional information

The mentioned line 927 of Editor.gd reads:

```gd
assert($World/Chunks.get_child_count() == 0)
```

**Comment by nalquas** [comment]
Further testing shows that restarting between steps 1 and 2 does not fix the issue for me / is not a valid workaround.

**Comment by nalquas** [comment]
I investigated this further. The assertion fails because a chunk, apparently the chunk with position (0,0,0), has not been unloaded by the previous line 926 `$World.chunk_manager.save_and_unload_all_chunks()`.

This line calls chunk_manager's `save_and_unload_all_chunks`, which in turn calls `_unload_old_chunks`. Here, `chunks_to_unload` is set to `loader._loaded_chunks.duplicate()`, where loader is a ChunkLoaderInteractive. All chunks in that array are later unloaded correctly.

However, as the map has only just been created, the array (`chunks_to_unload`) is empty. Weirdly though, the only existing chunk (0,0,0), which is still visible via Godot Remote Explorer, is not listed in ChunkLoaderInteractive's `_loaded_chunks`.

So further investigation could start there. Some questions to start with:

- Why is chunk (0,0,0) loaded at this point?
- Why isn't chunk (0,0,0) listed in ChunkLoaderInteractive's `_loaded_chunks`?
- What does it mean that ChunkLoaderInteractive's `_currently_loading_chunk` is set to `chunk_0_0`?

**Comment by HaSa1002** [comment]
> Why is chunk (0,0,0) loaded at this point?

It is loaded with the scene file we copy from. But this scene file haven't been updated to the latest file format, I think.

> Why isn't chunk (0,0,0) listed in ChunkLoaderInteractive's _loaded_chunks?

Valid.

> What does it mean that ChunkLoaderInteractive's _currently_loading_chunk is set to chunk_0_0?

@DasCapschen do you know some more. I have the feeling if we `git blame` someone then it's gonna be me 😅

**Comment by HaSa1002** [comment]
Workaround is to just continue in editor and ignore the assert, I think

**Comment by DasCapschen** [comment]
ChunkLoaderInteractive is loading chunks not all at one, but like the LoadingScreen does it incrementally.     
So if `_curently_loading_chunk` is set to `chunk_0_0`, the ChunkLoaderInteractive has started loading the chunk, but is not finished yet.   
Since it's not finished loading yet, I would not expect it in `_loaded_chunks` and thus it cannot be unloaded.

The bug I don't think is with the ChunkLoader, but with the porting logic, which should not have been triggered at this point...

**Comment by DasCapschen** [comment]
Think I found the issue... it merges chunks if there are multiple with the same position, deleting duplicates from the tree and adding the one true chunk to `_loaded_chunks`.  
EXCEPT if there is only 1 possible chunk for that position, then it just skips it entirely, and crucially, DOESN'T add it to `_loaded_chunks`. Which means later in `save_and_unload_chunks`, it cannot be unloaded 😦 

EDIT:
Oh yeah, that's exactly what the PR fixes... gj 😂
