### ISSUE TITLE
Show Addon Folder does not work on macOS Sonoma (simulator v0.9 beta 1)

### ISSUE THREAD

**Issue by alopix** [Libre-TrainSim/Libre-TrainSim#552]
### Summary

The "Show Addon Folder" on macOS Sonoma results in an error message that the folder cannot be opened (see screenshot).

### How to reproduce

1. Go to 'Content'
2. Click on 'Show Addon Folder'
3. See error

### Observed behavior

Error popup.
<img width="282" alt="image" src="https://github.com/Libre-TrainSim/Libre-TrainSim/assets/124467/4b6a49cb-3eea-454d-84ef-e76600040fa9">

### Expected behavior

The folder to open.

### Version

- Game Version: 0.9 beta 1
- OS: macOS Sonoma

### Additional information

This is complete clean installation. I downloaded the beta a few minutes ago after learning that the included scenarios did not load in v0.8 on macOS.

**Comment by HaSa1002** [comment]
Ok good to know. Afaik none of us has a mac to test upon. IIRC the addons should have been located in a user folder so I am not immediately sure why this happens

**Comment by alopix** [comment]
There is a folder called `/Users/<myusername>/Library/Application Support/libre_train_sim` with the expected folders I assume. Not sure what command fails to send the correct folder to open on that button click.
<img width="191" alt="image" src="https://github.com/Libre-TrainSim/Libre-TrainSim/assets/124467/4736b802-22dc-48fc-8c9f-e0ca64d31123">

**Comment by alopix** [comment]
I created a PR that would resolve this.
