### ISSUE TITLE
Language Submission Brazilian Portuguese

### ISSUE THREAD

**Issue by RafaMGam** [Libre-TrainSim/Libre-TrainSim#555]
[ptbr.zip](https://github.com/Libre-TrainSim/Libre-TrainSim/files/14876833/ptbr.zip)

Hello!

I'm submitting the files with the translation for Brazilian Portuguese, please let me know if there's anything that needs to be changed.

**Comment by HaSa1002** [comment]
Hey @RafaMGam thanks for the work.
Sadly we never updated the old documentation so this is gonna turn to be quite a bit of work for one of us to integrate. However that's not your fault. I hope someone of @Libre-TrainSim/dev on Linux has better tooling than I do. I'd appreciate not integrating these files myself. For me that's a bit more work 😅 

So to reiterate, the change is very welcome, it just gonna take a bit of work on our side to integrate it.

For future updates, please refer to this documentation page: https://docs.libretrainsim.org/en/latest/contribute/translations/

**Comment by Jomosoto** [comment]
I can integrate it later today 👍
