### ISSUE TITLE
Camera Drive "Feeling" in Cabin

### ISSUE THREAD

**Issue by Jean28518** [Libre-TrainSim/Libre-TrainSim#60]

**Comment by comick** [comment]
@Jean28518  what are your ideas here? Having done some work on cameras, I may help.

**Comment by Jean28518** [comment]
Hey @comick thank you!
When you sit in the cabin, the camera doesn't move unless your acceleration changes.
I think it would be more realistic, if the camera moves randomly a bit up/down left/right when the speed of the train is high. That should geive more realistic Feeling in the cabin.
Do you know what I mean?

This feature could be added to the wagon camers too..

**Comment by comick** [comment]
I'll take a look into something realistic, time allowing, and maybe factor cabin camera together with the other cameras.

**Comment by Jean28518** [comment]
Thank you very much!
Please keep me updated with this

**Comment by Jean28518** [comment]
Hey @comick How is the work going?
If you don't want to develop further on for this issue, just let me know it.

Then I will implement this Feature

**Comment by comick** [comment]
Hey, still around but with little time. I'd still like to take a look though! If you have other things to be implement I should still be able to go for this one
