### ISSUE TITLE
Apple: .pck Files can not be accessed. 

### ISSUE THREAD

**Issue by SeaMac** [Libre-TrainSim/Libre-TrainSim#64]
Folder for .pck content files not writeable.
I downloaded version 0.7 and it is TOO LARGE for my limited display size - the items on the right hand edge are not visible.
You need to make screen resolutions possible and allow for lo-rez 800X600 displays if you are going to be playable on mirrored projector displays. It does NOT honor when I uncheck the "Fullscreen" button in settings - it ignores that setting!!!!

When you click the content button there is a message at the top stating that .pck files need to be placed in a subfolder of private/var/folders/blah-blah-blah/I6/T/ ...... in order to be loaded: and that location is NOT Writeable by the user.
You simply CANNOT move or paste those .pck files to that location. So there are NO Tracks in the "Play" window. No Content can be added and the Game does Not Play.

![image](https://user-images.githubusercontent.com/5051781/102963372-c58f7700-449d-11eb-982c-b1671d912405.png)

**Comment by Jean28518** [comment]
So the Apple Version does not work properly..
Sorry. I don't know how to fix, because I don't have any Apple device at home.
Maybe someone else in the community can help.

For the display problem I created a new Issue.
I will fix that soon.

Thanks for reporting the bug!

**Comment by SeaMac** [comment]
The standard location that developers typically use on Apple devices is to have your App check in Library/Application Support/ (Or the Library/Application Support/ folder in the Users Home Folder) and see if there is a Libre TrainSim Folder in there already ... if not it CREATES a Libre TrainSim Folder in that location and installs the default templates / creates a folder specifically FOR PCK Files. The user can Always add Layouts (Or Create new ones) in the Library/Application Support/Libre TrainSim/PCK/ Folder (And you write your App to expect all data files in Library/Application Support/Libre TrainSim/ ... ).

This is kinda the "Standard" App Developers location to stash data files (On Apple devices) ... everyone gets to "Write" a directory in "Library/Application Support/" for their OWN App and fill it with subdirectories and templates and resources of their own. You should Consider an "Application Support" Location in Linux and Windows Builds also ... so your users have a writable location to add PCK Files to. (By Drag&Drop or Copy/Paste most commonly)

You gotta add a little code in your app that initializes the templates and data resources ... the first thing it does is check root/Library/Application Support/ and/or (users home folder)/Library/Application Support/ for a  Libre TrainSim folder ... and if not finding it there: to create it and populate it with your substitute-able resources (Graphics/Tracks/Preferences) ... first time. IF the folder is there: you skip over the initialization code and proceed to main loop.   Be Sure to copy any resources that need to be writable into Application Support/Libre TrainSim. 

(This is how I would code it. I do daydream in flowcharts but don't know too many coding languages or I'd pitch in actual code: rather than describe the standard routines that most Apple Apps use by convention.)
