### ISSUE TITLE
Language Submission (Japanese)

### ISSUE THREAD

**Issue by paontv** [Libre-TrainSim/Libre-TrainSim#66]
The letter doesn't show up. It seems that the font is not supported.

https://drive.google.com/drive/folders/1QREpHD6vGnRxAsG30lLVqK6IQ-ZZeGSX?usp=sharing

**Comment by Jean28518** [comment]
Thank you very much!
I fixed that issue.
![grafik](https://user-images.githubusercontent.com/39700889/103138105-847ea900-46cf-11eb-854c-33393e6d122a.png)
