### ISSUE TITLE
Mobile Version

### ISSUE THREAD

**Issue by Jean28518** [Libre-TrainSim/Libre-TrainSim#69]

**Comment by bodamat** [comment]
Oh, great :) I'll want to try export to Android. I'll write my result :)

**Comment by Jean28518** [comment]
Great! I will do this in the end of developint 0.8, i think...

**Comment by bodamat** [comment]
> Great! I will do this in the end of developint 0.8, i think...

I think I too :) I want to help you with important tasks :)
