### ISSUE TITLE
Possibility of driving backwards

### ISSUE THREAD

**Issue by simfann** [Libre-TrainSim/Libre-TrainSim#77]
Sometimes it's very helpful to have a possibility to drive backwards. For example when you have missed a station or you have braked too late at the station or at a red signal and want to correct that situation by driving back. Else the scenario will come to an end without a possibility to cancel your mistake.

**Comment by Jean28518** [comment]
Thanks for your idea!

I will think about it, how to implement this :)

**Comment by DasCapschen** [comment]
I will look into this and start working on it :)
