### ISSUE TITLE
Loading Tracks

### ISSUE THREAD

**Issue by ghost** [Libre-TrainSim/Libre-TrainSim#78]
Hi, I have recently downloaded this game and was looking forward to playing it. BUT...
I have added content packs by dragging them into /Applications/Libre TrainSim.app/Contents/MacOS and they show up in the content manager but not the play section. I have restarted the Sim multiple times and it hasn't changed anything. Is this normal?

**Comment by Jean28518** [comment]
Thanks for your issue!
Similar Problem as in #64 
Sorry, I don't have a mac for debugging this out.

So here we need further help ;)
