### ISSUE TITLE
Flatpak for distribution on flathub.

### ISSUE THREAD

**Issue by librebob** [Libre-TrainSim/Libre-TrainSim#90]
Hi,

I was wondering if you have any interest in distributing this game. If you are interested I can have a go at creating a flatpak manifest to allow it to be distributed on flathub. This would make the game easily available to people on a range of GNU/Linux distributions.

Here's a list of the currently available software tagged as a game on flathub.
https://flathub.org/apps/category/Game

**Comment by Jean28518** [comment]
Thanks for your offer!
But we are already at flathub: https://flathub.org/apps/details/org.libretrainsim.Libre-TrainSim
If you see some errors are have improvement ideas, you are welcome!
https://github.com/flathub/org.libretrainsim.Libre-TrainSim

**Comment by librebob** [comment]
Awesome! Can't wait to check it out!
